FUZZER_NAME := "forkserver_simple_rs"
CARGO_TARGET_DIR := env("CARGO_TARGET_DIR", "target")
PROFILE := env("PROFILE", "release")
PROFILE_DIR := if PROFILE == "release" { "release" } else if PROFILE == "dev" { "debug" } else { "debug" }
FUZZER := CARGO_TARGET_DIR / PROFILE_DIR / FUZZER_NAME
CORPUS := "corpus"

build:
    cargo build --profile {{ PROFILE }}

run: build
    {{ FUZZER }} {{ CORPUS }}

test: build
    #!/bin/bash
    timeout 15s {{ FUZZER }} {{ CORPUS }} | tee fuzz_stdout.log || true
    if grep -qa "objectives: 1" fuzz_stdout.log; then
        echo "Fuzzer is working"
    else
        echo "Fuzzer does not generate any testcases or any crashes"
        exit 1
    fi

run-persistent: build
    {{ FUZZER }} {{ CORPUS }} -p

test-persistent: build
    #!/bin/bash
    timeout 10s {{ FUZZER }} {{ CORPUS }} -p | tee fuzz_persistent_stdout.log || true
    if grep -qa "objectives: 1" fuzz_persistent_stdout.log; then
        echo "Fuzzer is working"
    else
        echo "Fuzzer does not generate any testcases or any crashes"
        exit 1
    fi

clean:
    cargo clean
