FUZZER_NAME := "forkserver_simple_rs"
CARGO_TARGET_DIR := env("CARGO_TARGET_DIR", "target")
PROFILE := env("PROFILE", "release")
PROFILE_DIR := if PROFILE == "release" { "release" } else if PROFILE == "dev" { "debug" } else { "debug" }
FUZZER := CARGO_TARGET_DIR / PROFILE_DIR / FUZZER_NAME
CORPUS := "corpus"

build:
    cargo build --profile {{ PROFILE }}

build-shmem:
    cargo build --profile {{ PROFILE }} --features shared_input_mem

run: build
    {{ FUZZER }} {{ CORPUS }}

test-shmem: build-shmem
    #!/bin/bash
    timeout 30s {{ FUZZER }} {{ CORPUS }} | tee fuzz_shmem_stdout.log || true
    if grep -qa "objectives: 1" fuzz_shmem_stdout.log; then
        echo "Fuzzer (shmem) is working"
    else
        echo "Fuzzer (shmem) does not generate any testcases or any crashes"
        exit 1
    fi

test: test-shmem build
    #!/bin/bash
    timeout 30s {{ FUZZER }} {{ CORPUS }} | tee fuzz_stdout.log || true
    if grep -qa "objectives: 1" fuzz_stdout.log; then
        echo "Fuzzer is working"
    else
        echo "Fuzzer does not generate any testcases or any crashes"
        exit 1
    fi

run-persistent: build
    {{ FUZZER }} {{ CORPUS }} -p

test-persistent: build
    #!/bin/bash
    timeout 10s {{ FUZZER }} {{ CORPUS }} -p | tee fuzz_persistent_stdout.log || true
    if grep -qa "objectives: 1" fuzz_persistent_stdout.log; then
        echo "Fuzzer is working"
    else
        echo "Fuzzer does not generate any testcases or any crashes"
        exit 1
    fi

clean:
    cargo clean
