mod libafl_bolts 'crates/libafl_bolts/Justfile'
mod libafl 'crates/libafl/Justfile'
mod libafl_targets 'crates/libafl_targets/Justfile'
mod libafl_cc 'crates/libafl_cc/Justfile'
mod libafl_derive 'crates/libafl_derive/Justfile'
mod libafl_nyx 'crates/libafl_nyx/Justfile'
mod build_id2 'crates/build_id2/Justfile'
mod core_affinity2 'crates/core_affinity2/Justfile'
mod exceptional 'crates/exceptional/Justfile'
mod fast_rands 'crates/fast_rands/Justfile'
mod libafl_core 'crates/libafl_core/Justfile'
mod libafl_intelpt 'crates/libafl_intelpt/Justfile'
mod libafl_sugar 'crates/libafl_sugar/Justfile'
mod libafl_tinyinst 'crates/libafl_tinyinst/Justfile'
mod libafl_unicorn 'crates/libafl_unicorn/Justfile'
mod ll_mp 'crates/ll_mp/Justfile'
mod minibsod 'crates/minibsod/Justfile'
mod no_std_time 'crates/no_std_time/Justfile'
mod ownedref 'crates/ownedref/Justfile'
mod serde_anymap 'crates/serde_anymap/Justfile'
mod shmem_providers 'crates/shmem_providers/Justfile'
mod tuple_list_ex 'crates/tuple_list_ex/Justfile'
mod libafl_libfuzzer 'crates/libafl_libfuzzer/Justfile'
mod libafl_concolic_symcc_runtime 'crates/libafl_concolic/symcc_runtime/Justfile'
mod libafl_concolic_dump_constraints 'crates/libafl_concolic/test/dump_constraints/Justfile'
mod libafl_concolic_runtime_test 'crates/libafl_concolic/test/runtime_test/Justfile'
mod libafl_concolic_symcc_libafl 'crates/libafl_concolic/symcc_libafl/Justfile'
mod libafl_asan 'crates/libafl_asan/Justfile'
mod libafl_asan_fuzz 'crates/libafl_asan/libafl_asan_fuzz/Justfile'
mod libafl_asan_libc 'crates/libafl_asan/libafl_asan_libc/Justfile'
mod libafl_qemu_runner 'crates/libafl_qemu/libafl_qemu_runner/Justfile'
mod libafl_qemu_build 'crates/libafl_qemu/libafl_qemu_build/Justfile'
mod libafl_qemu_sys 'crates/libafl_qemu/libafl_qemu_sys/Justfile'
mod libvharness_sys 'crates/libafl_qemu/libvharness_sys/Justfile'
mod libafl_qemu 'crates/libafl_qemu/Justfile'
mod libafl_frida 'crates/libafl_frida/Justfile'

doc-all:
  just libafl_bolts doc
  just libafl doc
  just libafl_targets doc
  just libafl_cc doc
  just libafl_derive doc
  just libafl_nyx doc
  just build_id2 doc
  just core_affinity2 doc
  just exceptional doc
  just fast_rands doc
  just libafl_core doc
  just libafl_intelpt doc
  just libafl_sugar doc
  just libafl_tinyinst doc
  just libafl_unicorn doc
  just ll_mp doc
  just minibsod doc
  just no_std_time doc
  just ownedref doc
  just serde_anymap doc
  just shmem_providers doc
  just tuple_list_ex doc
  just libafl_libfuzzer doc
  just libafl_asan doc
  just libafl_asan_fuzz doc
  just libafl_asan_libc doc
  just libafl_qemu_runner doc
  just libafl_qemu_build doc
  just libafl_qemu_sys doc
  just libvharness_sys doc
  just libafl_qemu doc
  just libafl_concolic_symcc_runtime doc
  just libafl_concolic_dump_constraints doc
  just libafl_concolic_runtime_test doc
  just libafl_concolic_symcc_libafl doc
  just libafl_frida doc