install_llvm_tools:
    rustup toolchain install nightly --component llvm-tools-preview

install_cargo_fuzz:
    cargo install cargo-fuzz

build: install_cargo_fuzz install_llvm_tools
    cargo +nightly fuzz build --target-dir fuzz/target fuzz_target_1

[linux]
test: build
    #!/bin/bash
    rm -rf fuzz/artifacts fuzz/corpus fuzz_stdout.log || true
    timeout 45s cargo +nightly fuzz run --target-dir fuzz/target fuzz_target_1 > fuzz_stdout.log 2>&1 || true
    cat fuzz_stdout.log
    if grep -qa "objectives: 1" fuzz_stdout.log || grep -qa "deadlysignal" fuzz_stdout.log; then
        echo "Fuzzer is working"
    else
        echo "Fuzzer does not generate any testcases or any crashes"
        exit 1
    fi

[macos]
[windows]
test: build
    echo "Unsupported on this platform"

clean:
    rm -rf fuzz/target
