/* Generated by hand by Fioraldi bindgen */

#[repr(C)]
#[derive(Copy, Clone)]
pub struct x86_regs {
    pub eax: u32,
    pub ebx: u32,
    pub ecx: u32,
    pub edx: u32,
    pub edi: u32,
    pub esi: u32,
    pub ebp: u32,
    pub eip: u32,
    pub esp: u32,
    pub eflags: u32,
    pub xmm_regs: [[u8; 8usize]; 16usize],
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct x86_64_regs {
    pub rax: u64,
    pub rbx: u64,
    pub rcx: u64,
    pub rdx: u64,
    pub rdi: u64,
    pub rsi: u64,
    pub rbp: u64,
    pub r8: u64,
    pub r9: u64,
    pub r10: u64,
    pub r11: u64,
    pub r12: u64,
    pub r13: u64,
    pub r14: u64,
    pub r15: u64,
    pub rip: u64,
    pub rsp: u64,
    pub rflags: u64,
    pub zmm_regs: [[u8; 32usize]; 64usize],
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct arm_regs {
    pub r0: u32,
    pub r1: u32,
    pub r2: u32,
    pub r3: u32,
    pub r4: u32,
    pub r5: u32,
    pub r6: u32,
    pub r7: u32,
    pub r8: u32,
    pub r9: u32,
    pub r10: u32,
    pub r11: u32,
    pub r12: u32,
    pub r13: u32,
    pub r14: u32,
    pub r15: u32,
    pub cpsr: u32,
    pub vfp_zregs: [[u8; 32usize]; 16usize],
    pub vfp_xregs: [u32; 16usize],
}

#[repr(C)]
#[derive(Copy, Clone)]
pub struct arm64_regs {
    pub x0: u64,
    pub x1: u64,
    pub x2: u64,
    pub x3: u64,
    pub x4: u64,
    pub x5: u64,
    pub x6: u64,
    pub x7: u64,
    pub x8: u64,
    pub x9: u64,
    pub x10: u64,
    pub x11: u64,
    pub x12: u64,
    pub x13: u64,
    pub x14: u64,
    pub x15: u64,
    pub x16: u64,
    pub x17: u64,
    pub x18: u64,
    pub x19: u64,
    pub x20: u64,
    pub x21: u64,
    pub x22: u64,
    pub x23: u64,
    pub x24: u64,
    pub x25: u64,
    pub x26: u64,
    pub x27: u64,
    pub x28: u64,
    pub x29: u64,
    pub x30: u64,
    pub x31: u64,
    pub pc: u64,
    pub cpsr: u32,
    pub vfp_zregs: [[u8; 32usize]; 256usize],
    pub vfp_pregs: [[u8; 17usize]; 32usize],
    pub vfp_xregs: [u32; 16usize],
}
