[package]
name = "libafl_intelpt"
version.workspace = true
authors = ["Marco Cavenati <cavenatimarco@gmail.com>"]
description = "Intel Processor Trace wrapper for libafl"
repository = "https://github.com/AFLplusplus/LibAFL/"
edition = "2024"
license.workspace = true
readme = "./README.md"
keywords = ["fuzzing", "testing", "security", "intelpt"]
categories = ["development-tools::testing", "no-std"]

[features]
default = ["std"]
std = ["libafl_bolts/std"]

## Export raw Intel PT traces on decode, useful for debug, disabled by default for best performance
export_raw = []

[dev-dependencies]
static_assertions = { workspace = true }
proc-maps = "0.4.0"
env_logger = "0.11.10"

[target.'cfg(target_os = "linux" )'.dev-dependencies]
nix = { workspace = true }

[dependencies]
arbitrary-int = { workspace = true }
bitbybit = { workspace = true }
libafl_bolts = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
num_enum = { workspace = true, default-features = false }
num-traits = { workspace = true, default-features = false }
ptcov = { version = "0.1.3" }
raw-cpuid = { version = "11.6.0" }

[target.'cfg(target_os = "linux" )'.dependencies]
caps = { version = "0.5.6" }
perf-event-open-sys = { version = "6.0.0" }

[target.'cfg(target_os = "windows" )'.dependencies]
windows = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_System_Threading",
] }
ipt = { version = "0.1.3" }

[lints]
workspace = true
