[package]
name = "intel_pt_command_executor"
version = "0.1.0"
authors = ["Marco Cavenati <cavenatimarco@gmail.com>"]
edition = "2021"

[dependencies]
env_logger = "0.11.11"
libafl = { path = "../../../crates/libafl", features = ["intel_pt"] }
libafl_bolts = { path = "../../../crates/libafl_bolts" }
log = { version = "0.4.33" }
object = "0.40.0"

[profile.release]
lto = true
codegen-units = 1
debug = true
