[package]
name = "gdb_demo"
version = "0.16.0"
edition = "2024"

[build-dependencies]
vergen = { version = "10.0.1", features = ["build", "cargo", "rustc", "si"] }
vergen-git2 = "10.0.1"

[dependencies]
clap = { version = "4.5", default-features = false, features = [
  "derive",
  "string",
  "std",
  "help",
] }
