[env]
TARGET_DIR = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}"

[env.development]
PROFILE_DIR = "debug"

[env.release]
PROFILE_DIR = "release"

[tasks.target_dir]
condition = { files_not_exist = ["${TARGET_DIR}"] }
script_runner = "@shell"
script = '''
mkdir -p ${TARGET_DIR}
'''

[tasks.ram_disk]
script = """
sudo mkdir -p /mnt/libafl_qemu_tmpfs || echo "/mnt/libafl_qemu_tmpfs creation failed";
sudo mount -o size=128M -t tmpfs none /mnt/libafl_qemu_tmpfs || echo "tmpfs mount failed";
sudo chown $(id -u):$(id -g) "/mnt/libafl_qemu_tmpfs";
"""

[tasks.build_target]
dependencies = ["target_dir"]
command = "nasm"
args = [
  "-o",
  "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/boot.bin",
  "${CARGO_MAKE_WORKING_DIRECTORY}/src/boot.s",
]

[tasks.build_fuzzer]
command = "cargo"
args = ["build", "--profile", "${CARGO_MAKE_CARGO_PROFILE}"]

[tasks.build]
dependencies = ["build_fuzzer", "build_target"]

[tasks.convert_target_image]
command = "qemu-img"
args = [
  "convert",
  "-O",
  "qcow2",
  "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/boot.bin",
  "/mnt/libafl_qemu_tmpfs/boot.qcow2",
]
dependencies = ["build_target", "ram_disk"]

[tasks.setcap]
script = "sudo setcap cap_ipc_lock,cap_sys_ptrace,cap_sys_admin,cap_syslog=ep ${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/${PROFILE_DIR}/${CARGO_MAKE_CRATE_NAME}"
dependencies = ["build_fuzzer"]

[tasks.run]
dependencies = ["build", "setcap", "convert_target_image"]
script = """
${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/${PROFILE_DIR}/${CARGO_MAKE_CRATE_NAME}
sudo umount /mnt/libafl_qemu_tmpfs;
sudo rm -r /mnt/libafl_qemu_tmpfs
"""

[tasks.default]
alias = "run"
