FUZZER_NAME := 'fuzzer_wasm'
PROJECT_DIR := absolute_path(".")
PROFILE := 'release'
PROFILE_DIR := if PROFILE == "release" { "release" } else if PROFILE == "dev" { "debug" } else { "debug" }
CARGO_TARGET_DIR := env("CARGO_TARGET_DIR", "target")
FUZZER := CARGO_TARGET_DIR / PROFILE_DIR / FUZZER_NAME
LIBAFL_CC := CARGO_TARGET_DIR / PROFILE_DIR / "libafl_cc"

build:
    cargo build --target web

[linux]
[macos]
test:
    wasm-pack test --chrome --headless

[windows]
test:
    echo "Unsupported on this platform"

clean:
	cargo clean
