import "../../../just/libafl-qemu-libpng.just"

FUZZER_NAME := "qemu_launcher"

HARNESS := TARGET_DIR / ("libpng-harness-" + PROFILE)

[unix]
build arch=DEFAULT_ARCH:
    cargo build \
      --profile {{ PROFILE }} \
      --features {{ arch }} \
      --target-dir {{ TARGET_DIR }}

[unix]
harness arch=DEFAULT_ARCH: (libpng arch)
    {{ CROSS_CXX }} \
        ./harness.cc \
        {{ CROSS_CFLAGS }} \
        "{{ TARGET_DIR }}/build-png/.libs/libpng16.a" \
        "{{ TARGET_DIR }}/build-zlib/libz.a" \
        -I"{{ TARGET_DIR }}/build-png" \
        -I"{{ TARGET_DIR }}/build-zlib/zlib/lib" \
        -L"{{ TARGET_DIR }}/build-zlib/zlib/lib" \
        -o"{{ HARNESS }}" \
        -lm

[unix]
run arch=DEFAULT_ARCH: (harness arch) (build arch)
    {{ FUZZER }} \
        --input ./corpus \
        --output {{ TARGET_DIR }}/output/ \
        --log {{TARGET_DIR}}/output/log.txt \
        --cores 0-7 \
        --asan-cores 0-3 \
        --cmplog-cores 2-5 \
        --iterations 1000000 \
        --tui \
        -- \
        {{ HARNESS }}


[unix]
test_inner arch=DEFAULT_ARCH : (run arch)
    #!/bin/bash

    export QEMU_LAUNCHER={{ FUZZER }}

    ./tests/injection/test.sh || exit 1

    # complie again with simple mgr
    cargo build --profile={{PROFILE}} --features="simplemgr" --target-dir={{ TARGET_DIR }}
    ./tests/qasan/test.sh || exit 1

[unix]
test: (test_inner "x86_64") (test_inner "arm")

single arch=DEFAULT_ARCH: (harness arch) (build arch)
    {{ FUZZER }} \
        --input ./corpus \
        --output {{ TARGET_DIR }}/output/ \
        --log {{ TARGET_DIR }}/output/log.txt \
        --cores 0 \
        -- \
        {{ HARNESS }}

asan arch=DEFAULT_ARCH: (harness arch) (build arch)
    {{ FUZZER }} \
        --input ./corpus \
        --output {{ TARGET_DIR }}/output/ \
        --log {{ TARGET_DIR }}/output/log.txt \
        --cores 0 \
        --asan-cores 0 \
        -- \
        {{ HARNESS }}

asan_guest arch=DEFAULT_ARCH: (harness arch) (build arch)
    {{ FUZZER }} \
        --input ./corpus \
        --output {{ TARGET_DIR }}/output/ \
        --log {{ TARGET_DIR }}/output/log.txt \
        --cores 0 \
        --asan-guest-cores 0 \
        -- \
        {{ HARNESS }}

[unix]
clean:
    cargo clean