import "../../../just/libafl-qemu.just"

FUZZER_NAME := "qemu_cmin"

CROSS_CC := env("CROSS_CC", "x86_64-linux-gnu-gcc")
CROSS_CXX := env("CROSS_CXX", "x86_64-linux-gnu-g++")
CROSS_CFLAGS := env("CROSS_CFLAGS", "")

DEFAULT_ARCH := env("LIBPNG_ARCH", "x86_64")
OPTIMIZATIONS := env("LIBPNG_OPTIMIZATIONS", "yes")

DEPS_DIR := TARGET_DIR / "deps"

HARNESS := TARGET_DIR / ("libpng-harness-" + PROFILE)

# FEATURE = "x86_64"
# LIBAFL_QEMU_CLONE_DIR = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/qemu-libafl-bridge"

[unix]
target_dir:
    mkdir -p {{ TARGET_DIR }}

[unix]
deps_dir:
    mkdir -p {{ DEPS_DIR }}

[unix]
arch_dir arch:
    mkdir -p {{ arch }}

[unix]
zlib_wget: deps_dir
    #!/bin/bash

    wget \
        -O "{{ DEPS_DIR }}/zlib-1.2.13.tar.gz" \
        https://zlib.net/fossils/zlib-1.2.13.tar.gz

    tar \
        zxvf {{ DEPS_DIR }}/zlib-1.2.13.tar.gz \
        -C {{ DEPS_DIR }}

[unix]
zlib: zlib_wget
    #!/bin/bash

    rm -rf {{ TARGET_DIR }}/build-zlib/

    mkdir {{ TARGET_DIR }}/build-zlib/

    cd {{ TARGET_DIR }}/build-zlib/ && \
        CC={{ CROSS_CC }} \
        CFLAGS={{ CROSS_CFLAGS }} \
        {{ DEPS_DIR }}/zlib-1.2.13/configure \
            --prefix=./zlib

    make -j install

[unix]
libpng_wget: deps_dir
    wget \
        -O "{{ DEPS_DIR }}/v1.6.37.tar.gz" \
        https://github.com/glennrp/libpng/archive/refs/tags/v1.6.37.tar.gz

    tar \
        -xvf "{{ DEPS_DIR }}/v1.6.37.tar.gz" \
        -C {{ DEPS_DIR }}

[unix]
libpng arch=DEFAULT_ARCH: (arch_dir arch) zlib libpng_wget
    rm -rf {{ TARGET_DIR }}/build-png/

    mkdir {{TARGET_DIR}}/build-png/

    cd {{TARGET_DIR}}/build-png/ && \
        CC={{ CROSS_CC }} \
        CFLAGS="{{ CROSS_CXX }} -I"{{ TARGET_DIR }}/build-zlib/zlib/lib"" \
        LDFLAGS=-L"{{ TARGET_DIR }}/build-zlib/zlib/lib" \
        {{ DEPS_DIR }}/libpng-1.6.37/configure \
            --enable-shared=no \
            --with-pic=yes \
            --enable-hardware-optimizations={{OPTIMIZATIONS}} \
            --host={{ arch }} \

    make -j

[unix]
build arch=DEFAULT_ARCH:
    cargo build \
      --profile {{ PROFILE }} \
      --features {{ arch }} \
      --target-dir {{ TARGET_DIR }}

[unix]
harness arch=DEFAULT_ARCH: (libpng arch)
    {{ CROSS_CXX }} \
        ./harness.cc \
        {{ CROSS_CFLAGS }} \
        {{TARGET_DIR}}/build-png/.libs/libpng16.a" \
        "{{TARGET_DIR}}/build-zlib/libz.a" \
        -I"{{TARGET_DIR}}/build-png" \
        -I"{{TARGET_DIR}}/build-zlib/zlib/lib" \
        -L"{{TARGET_DIR}}/build-zlib/zlib/lib" \
        -o"{{ HARNESS }}" \
        -lm -static

[unix]
run arch=DEFAULT_ARCH: (harness arch) (build arch)
    {{ FUZZER }} \
        --coverage-path {{ TARGET_DIR }}/cov.drcov \
        --input-dir ./corpus \
        --verbose \
        -- {{ HARNESS }}

[unix]
test_inner arch=DEFAULT_ARCH : (run arch)
    #!/bin/bash

    cargo run --manifest-path ../../../utils/drcov_utils/Cargo.toml --bin drcov_merge -- \
        -i {{ TARGET_DIR }}/cov-000.drcov {{ TARGET_DIR }}/cov-001.drcov {{TARGET_DIR }}/cov-002.drcov {{ TARGET_DIR }}/cov-003.drcov \
        --output {{ TARGET_DIR }}/cov-merged.drcov || exit 1

    NB_BLOCKS=$(cargo run --manifest-path ../../../utils/drcov_utils/Cargo.toml --bin drcov_dump_addrs -- \
        -i {{ TARGET_DIR }}/cov-merged.drcov -a | wc -l || exit 1)

    echo "Nb blocks found: $NB_BLOCKS"

    if [ $NB_BLOCKS -ge 1700 ]; then
    echo "Test succeeded"
    else
    echo "Did not find more than 1700 blocks."
    exit 1
    fi

[unix]
test: (test_inner "x86_64") (test_inner "arm")

[unix]
clean:
    cargo clean