# Variables
[env]
FUZZER_NAME='fuzzer_mozjpeg'
LIBAFL_CC = './target/release/libafl_cc'
LIBAFL_CXX = './target/release/libafl_cxx'
FUZZER = './target/release/${FUZZER_NAME}'
PROJECT_DIR = { script = ["pwd"] }

[tasks.unsupported]
script_runner="@shell"
script='''
echo "Cargo-make not integrated yet on this platform"
'''

# libpng
[tasks.mozjpeg]
linux_alias = "unix_mozjpeg"
mac_alias = "unix_mozjpeg"
windows_alias = "unsupported"

[tasks.unix_mozjpeg]
condition = { files_not_exist = ["./mozjpeg-4.0.3"]}
script_runner="@shell"
script='''
wget https://github.com/mozilla/mozjpeg/archive/v4.0.3.tar.gz
tar -xzvf v4.0.3.tar.gz
'''

# Compilers
[tasks.cxx]
linux_alias = "unix_cxx"
mac_alias = "unix_cxx"
windows_alias = "unsupported"

[tasks.unix_cxx]
condition = { files_not_exist = ["${LIBAFL_CXX}"] }
command = "cargo"
args = ["build" , "--release"]

[tasks.cc]
linux_alias = "unix_cc"
mac_alias = "unix_cc"
windows_alias = "unsupported"

[tasks.unix_cc]
condition = { files_not_exist = ["${LIBAFL_CC}"] }
command = "cargo"
args = ["build" , "--release"]

# Library
[tasks.lib]
linux_alias = "unix_lib"
mac_alias = "unix_lib"
windows_alias = "unsupported"

[tasks.unix_lib]
script='''
cd mozjpeg-4.0.3 && cmake . -DENABLE_SHARED=false -DCMAKE_C_COMPILER=${PROJECT_DIR}/${LIBAFL_CC} -DCMAKE_CXX_COMPILER=${PROJECT_DIR}/${LIBAFL_CXX} -G "Unix Makefiles"
cd ${PROJECT_DIR}
make -C mozjpeg-4.0.3
'''
dependencies = [ "mozjpeg", "cxx", "cc" ]


# Harness
[tasks.fuzzer]
linux_alias = "unix_fuzzer"
mac_alias = "unix_fuzzer"
windows_alias = "unsupported"

[tasks.unix_fuzzer]
script_runner="@shell"
script='''
cargo build --release
	target/release/libafl_cxx \
		${PROJECT_DIR}/harness.cc \
		${PROJECT_DIR}/mozjpeg-4.0.3/*.a \
		-I${PROJECT_DIR}/mozjpeg-4.0.3/ \
		-o ${FUZZER_NAME} \
		-lm -lz
'''
dependencies = [ "lib", "cxx", "cc" ]

# Run the fuzzer
[tasks.run]
linux_alias = "unix_run"
mac_alias = "unix_run"
windows_alias = "unsupported"

[tasks.unix_run]
script_runner = "@shell"
script='''
./${FUZZER_NAME} &
sleep 0.2
./${FUZZER_NAME}
'''
dependencies = [ "fuzzer" ]

# Test
[tasks.test]
linux_alias = "linux_test"
mac_alias = "mac_test"
windows_alias = "unsupported"

[tasks.linux_test]
script_runner = "@shell"
script='''
rm -rf libafl_unix_shmem_server || true
timeout 11s ./${FUZZER_NAME} &
sleep 0.2
timeout 10s ./${FUZZER_NAME} >/dev/null 2>/dev/null &
'''
dependencies = [ "fuzzer" ]

[tasks.mac_test]
script='''
echo "Skipping build on MacOS as libpng in Github is ancient, see LibAFL GH issue #254"
'''

# Clean up
[tasks.clean]
linux_alias = "unix_clean"
mac_alias = "unix_clean"
windows_alias = "unsupported"

[tasks.unix_clean]
# Disable default `clean` definition
clear = true
script_runner="@shell"
script='''
rm -f ./${FUZZER_NAME}
make -C mozjpeg-4.0.3 clean
cargo clean
'''