import "../../../just/libafl.just"

FUZZER_NAME := "frida_fuzzer"
FUZZER_NAME_WIN := "frida_fuzzer.exe"

set windows-shell := ['cmd.exe', '/c']

libpng:
    {{ if os() == "windows" { "just _libpng_windows" } else { "just _libpng_unix" } }}

_libpng_unix:
    #!/bin/bash
    if [ ! -f v1.6.37.tar.gz ]; then
        wget https://github.com/glennrp/libpng/archive/refs/tags/v1.6.37.tar.gz
    fi
    tar -xvf v1.6.37.tar.gz

_libpng_windows:
    powershell -Command Invoke-WebRequest -OutFile libpng-1.6.37.tar.gz https://github.com/glennrp/libpng/archive/refs/tags/v1.6.37.tar.gz
    tar -xvf libpng-1.6.37.tar.gz
    del /q libpng-1.6.37.tar.gz

lib: libpng
    {{ if os() == "windows" { "just _lib_windows" } else { "just _lib_unix" } }}

_lib_unix:
    cd libpng-1.6.37 && ./configure --enable-shared=no --with-pic=yes --enable-hardware-optimizations=yes
    make -j -C libpng-1.6.37

_lib_windows:
    powershell -Command Invoke-WebRequest -OutFile zlib-1.2.11.tar.gz https://zlib.net/fossils/zlib-1.2.11.tar.gz
    tar -xvf zlib-1.2.11.tar.gz
    del /q zlib-1.2.11.tar.gz
    move zlib-1.2.11 zlib
    cd zlib && cmake -A x64 -DCMAKE_CXX_COMPILER=cl -DCMAKE_POLICY_VERSION_MINIMUM=3.5 . && cmake --build . --config Release

lib2: libpng
    {{ if os() == "windows" { "just _lib2_windows" } else { "echo 'No lib2 needed on Unix'" } }}

_lib2_windows:
    cd libpng-1.6.37 && cmake -A x64 -DCMAKE_CXX_COMPILER=cl -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DZLIB_ROOT=..\zlib -DZLIB_LIBRARY=..\zlib\Release\zlib.lib . && cmake --build . --config Release

harness: lib
    {{ if os() == "windows" { "just lib2 && just _harness_windows" } else { "just _harness_unix" } }}

_harness_unix:
    clang++ -O3 -c -fPIC harness.cc -o harness.o
    clang++ -O3 harness.o libpng-1.6.37/.libs/libpng16.a -shared -lz -o libpng-harness.so

_harness_windows:
    copy libpng-1.6.37\Release\libpng16.lib . && copy libpng-1.6.37\Release\libpng16.dll . && copy zlib\Release\zlib.lib . && copy zlib\Release\zlib.dll .
    cl /O2 /c /I .\libpng-1.6.37 harness.cc /Fo:harness.obj && link /DLL /OUT:libpng-harness.dll harness.obj libpng16.lib zlib.lib

build:
    cargo build --profile {{ PROFILE }}

run: build harness
    {{ if os() == "windows" { "just _run_windows" } else { "just _run_unix" } }}

_run_unix:
    {{ FUZZER }} -F LLVMFuzzerTestOneInput -H ./libpng-harness.so -l ./libpng-harness.so

_run_windows:
    {{ TARGET_DIR }}\{{ PROFILE }}\{{ FUZZER_NAME_WIN }} -F LLVMFuzzerTestOneInput -H .\libpng-harness.dll -l .\libpng-harness.dll -l .\zlib.dll -l .\libpng16.dll --cores=0

test: build harness
    {{ if os() == "windows" { "just _test_windows" } else { "just _test_unix" } }}

_test_unix:
    #!/bin/bash
    rm -rf libafl_unix_shmem_server || true
    timeout 30s {{ FUZZER }} -F LLVMFuzzerTestOneInput -H ./libpng-harness.so -l ./libpng-harness.so | tee fuzz_stdout.log 2>/dev/null || true
    if grep -qa "corpus: 70" fuzz_stdout.log; then
        echo "Fuzzer is working"
    else
        echo "Fuzzer does not generate any testcases or any crashes"
        exit 1
    fi

_test_windows:
    start "" "{{ TARGET_DIR }}\{{ PROFILE }}\{{ FUZZER_NAME_WIN }}" -F LLVMFuzzerTestOneInput -H .\libpng-harness.dll -l .\libpng-harness.dll -l .\zlib.dll -l .\libpng16.dll --cores=0
    ping -n 10 127.0.0.1>NUL && taskkill /im frida_fuzzer.exe /F
    dir /a-d corpus_discovered && (echo Files exist) || (exit /b 1337)

clean:
    {{ if os() == "windows" { "cargo clean" } else { "just _clean_unix" } }}

_clean_unix:
    #!/bin/bash
    if [ -d libpng-1.6.37 ]; then make -C libpng-1.6.37 clean; fi
    cargo clean

