{
 "title": "LibAFL Fuzzing Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Saved Solutions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "fuzzing{type=\"saved_solutions\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exec/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "fuzzing{type=\"execs_per_sec\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execs Done",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "fuzzing{type=\"execs_done\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Edges Found",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "fuzzing{type=\"edges_found\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Map Density",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "fuzzing{type=\"map_density\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Corpora Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "fuzzing{type=\"corpus_count\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Corpora Imported",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "fuzzing{type=\"corpus_imported\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Corpora Found",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "fuzzing{type=\"corpus_found\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "fuzzing{type=\"pending_total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Favs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "fuzzing{type=\"pending_favs\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}