//! Pure push-based stages for `LibAFL`.
//!
//! Unlike traditional stages where the stage executes inputs inside a loop, push stages
//! act as generator state machines. They yield [`ExecutionRequest`]s containing 1..N inputs
//! to be executed by the target executor, and receive execution observations in subsequent steps.

pub mod calibrate;
pub mod colorization;
#[cfg(feature = "std")]
pub mod dump;
pub mod dynamic;
pub mod generalization;
pub mod generation;
pub mod logics;
pub mod mutational;
pub mod power;
pub mod replay;
pub mod shadow;
#[cfg(feature = "std")]
pub mod sync;
pub mod time_tracker;
pub mod tmin;
pub mod tracing;
pub mod tuneable;
#[cfg(feature = "unicode")]
pub mod unicode;

#[cfg(feature = "std")]
pub mod verify_timeouts;

use core::fmt::Debug;

// Canonical Stage exports
pub use calibrate::{CalibrationPushStage, CalibrationStage};
pub use colorization::{ColorizationPushStage, ColorizationStage};
#[cfg(feature = "std")]
pub use dump::{DumpToDiskPushStage, DumpToDiskStage};
pub use dynamic::{DynamicPushStage, DynamicStage};
pub use generalization::{GeneralizationPushStage, GeneralizationStage};
pub use generation::{GenerationPushStage, GenerationStage};
use libafl_bolts::{Error, Named, tuples::HasConstLen};
pub use logics::{
    ClosurePushStage, ClosureStage, IfElsePushStage, IfElseStage, IfPushStage, IfStage,
    WhilePushStage, WhileStage,
};
pub use mutational::{
    MultiMutationalPushStage, MultiMutationalStage, StdMutationalPushStage, StdMutationalStage,
    StdTransformingMutationalPushStage, StdTransformingMutationalStage,
};
pub use power::{StdPowerMutationalPushStage, StdPowerMutationalStage};
pub use replay::{ReplayPushStage, ReplayStage};
use serde::{Deserialize, Serialize};
pub use shadow::{ShadowPushStage, ShadowStage, ShadowStage as ShadowTracingStage};
#[cfg(feature = "std")]
pub use sync::{SyncFromDiskPushStage, SyncFromDiskStage};
pub use time_tracker::{TimeTrackingPushStage, TimeTrackingStage};
pub use tmin::{StdTMinMutationalPushStage, StdTMinMutationalStage};
pub use tracing::{
    AflppCmplogTracingPushStage, AflppCmplogTracingStage, TracingPushStage, TracingStage,
};
pub use tuneable::{TuneableMutationalPushStage, TuneableMutationalStage};
#[cfg(feature = "unicode")]
pub use unicode::{UnicodeMutationalPushStage, UnicodeMutationalStage};
#[cfg(feature = "std")]
pub use verify_timeouts::{VerifyTimeoutsPushStage, VerifyTimeoutsStage};

use crate::{
    fuzzer::ExecutionRequest,
    stages::StageId,
    state::{HasCurrentStageId, Stoppable},
};

/// Serializable metadata storing progress of a push stage for deterministic restart and persistence.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct StageProgressMetadata {
    /// Total testcases / iterations planned for this stage round.
    pub testcases_to_do: usize,
    /// Testcases / iterations already completed.
    pub testcases_done: usize,
}

libafl_bolts::impl_serdeany!(StageProgressMetadata);

/// Step result yielded by a [`PushStage`].
#[derive(Debug, Clone)]
pub enum StageStep<I> {
    /// The stage generated inputs to execute.
    Execute(ExecutionRequest<I>),
    /// The stage has completed all iterations for the current corpus item.
    Done,
}

/// A stage generator.
pub trait Stage<EM, I, OT, S>: Named {
    /// Initialize the stage for the current corpus item.
    fn init(&mut self, state: &mut S, manager: &mut EM) -> Result<(), Error>;

    /// Advance the stage, generating the next execution request or signaling completion.
    fn step(&mut self, state: &mut S, manager: &mut EM) -> Result<StageStep<I>, Error>;

    /// Optional callback invoked after an execution observation for an input generated by this stage is processed.
    fn post_exec(
        &mut self,
        _state: &mut S,
        _manager: &mut EM,
        _obs: crate::fuzzer::BorrowedObservation<'_, I, OT>,
    ) -> Result<(), Error> {
        Ok(())
    }

    /// Cleanup the stage after all iterations for the current corpus item have completed.
    fn deinit(&mut self, state: &mut S, manager: &mut EM) -> Result<(), Error>;
}

/// Alias for [`Stage`].
pub use Stage as PushStage;

/// A tuple of [`Stage`]s executed sequentially.
pub trait StagesTuple<EM, I, OT, S> {
    /// Initialize stages.
    fn init_all(&mut self, state: &mut S, manager: &mut EM) -> Result<(), Error>;

    /// Advance through the tuple of stages.
    fn step_all(&mut self, state: &mut S, manager: &mut EM) -> Result<StageStep<I>, Error>;

    /// Invoke `post_exec` for a specific stage by index.
    fn post_exec_stage(
        &mut self,
        stage_idx: usize,
        state: &mut S,
        manager: &mut EM,
        obs: crate::fuzzer::BorrowedObservation<'_, I, OT>,
    ) -> Result<(), Error>;

    /// Cleanup all stages.
    fn deinit_all(&mut self, state: &mut S, manager: &mut EM) -> Result<(), Error>;
}

/// Alias for [`StagesTuple`].
pub use StagesTuple as PushStagesTuple;

impl<EM, I, OT, S> StagesTuple<EM, I, OT, S> for () {
    fn init_all(&mut self, _state: &mut S, _manager: &mut EM) -> Result<(), Error> {
        Ok(())
    }

    fn step_all(&mut self, _state: &mut S, _manager: &mut EM) -> Result<StageStep<I>, Error> {
        Ok(StageStep::Done)
    }

    fn post_exec_stage(
        &mut self,
        _stage_idx: usize,
        _state: &mut S,
        _manager: &mut EM,
        _obs: crate::fuzzer::BorrowedObservation<'_, I, OT>,
    ) -> Result<(), Error> {
        Ok(())
    }

    fn deinit_all(&mut self, _state: &mut S, _manager: &mut EM) -> Result<(), Error> {
        Ok(())
    }
}

impl<Head, Tail, EM, I, OT, S> StagesTuple<EM, I, OT, S> for (Head, Tail)
where
    Head: Stage<EM, I, OT, S>,
    Tail: StagesTuple<EM, I, OT, S> + HasConstLen,
    (Head, Tail): HasConstLen,
    S: HasCurrentStageId + Stoppable,
{
    fn init_all(&mut self, state: &mut S, manager: &mut EM) -> Result<(), Error> {
        match state.current_stage_id()? {
            Some(idx) if idx < StageId(Self::LEN) => self.1.init_all(state, manager),
            Some(idx) if idx == StageId(Self::LEN) => {
                self.0.init(state, manager)?;
                Ok(())
            }
            _ => {
                state.set_current_stage_id(StageId(Self::LEN))?;
                self.0.init(state, manager)?;
                Ok(())
            }
        }
    }

    fn step_all(&mut self, state: &mut S, manager: &mut EM) -> Result<StageStep<I>, Error> {
        let current_id = state.current_stage_id()?;

        match current_id {
            Some(idx) if idx == StageId(Self::LEN) => match self.0.step(state, manager)? {
                StageStep::Execute(mut req) => {
                    if req.tag.is_none() {
                        req.tag = Some(crate::fuzzer::ExecutionTag::new(Self::LEN - 1, 0));
                    }
                    Ok(StageStep::Execute(req))
                }
                StageStep::Done => {
                    self.0.deinit(state, manager)?;
                    state.clear_stage_id()?;
                    self.1.init_all(state, manager)?;
                    self.1.step_all(state, manager)
                }
            },
            Some(idx) if idx < StageId(Self::LEN) => self.1.step_all(state, manager),
            _ => {
                state.set_current_stage_id(StageId(Self::LEN))?;
                self.0.init(state, manager)?;
                match self.0.step(state, manager)? {
                    StageStep::Execute(mut req) => {
                        if req.tag.is_none() {
                            req.tag = Some(crate::fuzzer::ExecutionTag::new(Self::LEN - 1, 0));
                        }
                        Ok(StageStep::Execute(req))
                    }
                    StageStep::Done => {
                        self.0.deinit(state, manager)?;
                        state.clear_stage_id()?;
                        self.1.init_all(state, manager)?;
                        self.1.step_all(state, manager)
                    }
                }
            }
        }
    }

    fn post_exec_stage(
        &mut self,
        stage_idx: usize,
        state: &mut S,
        manager: &mut EM,
        obs: crate::fuzzer::BorrowedObservation<'_, I, OT>,
    ) -> Result<(), Error> {
        if stage_idx == Self::LEN - 1 {
            self.0.post_exec(state, manager, obs)
        } else {
            self.1.post_exec_stage(stage_idx, state, manager, obs)
        }
    }

    fn deinit_all(&mut self, state: &mut S, manager: &mut EM) -> Result<(), Error> {
        self.0.deinit(state, manager)?;
        self.1.deinit_all(state, manager)
    }
}

#[cfg(test)]
#[cfg(feature = "std")]
#[allow(
    clippy::type_complexity,
    clippy::match_wildcard_for_single_variants,
    clippy::duration_suboptimal_units
)]
mod tests {
    use alloc::vec;

    use libafl_bolts::{
        rands::StdRand,
        tuples::{RefIndexable, tuple_list},
    };

    use super::*;
    use crate::{
        common::HasMetadata,
        corpus::{Corpus, HasCurrentCorpusId, InMemoryCorpus, Testcase},
        events::NopEventManager,
        executors::{
            Executor, ExitKind, HasObservers,
            target::{DualTargetExecutor, TargetExecutor},
        },
        feedbacks::ConstFeedback,
        fuzzer::{EngineStep, ExecutionMode, FuzzingEngine, StdFuzzer},
        inputs::BytesInput,
        mutators::{mutations::BitFlipMutator, token_mutations::AflppRedQueen},
        observers::{StdMapObserver, map::CanTrack},
        schedulers::{
            IndexesLenTimeMinimizerScheduler, QueueScheduler,
            powersched::{PowerQueueScheduler, PowerSchedule},
        },
        stages::push::{
            CalibrationPushStage, MultiMutationalPushStage, StdMutationalPushStage,
            StdPowerMutationalPushStage, TracingPushStage,
        },
        state::StdState,
    };

    static mut OBS_MAP: [u8; 16] = [0; 16];

    #[derive(Debug)]
    struct DummyPrimaryExecutor {
        observers: (StdMapObserver<'static, u8, false>, ()),
    }

    impl HasObservers for DummyPrimaryExecutor {
        type Observers = (StdMapObserver<'static, u8, false>, ());

        fn observers(&self) -> RefIndexable<&Self::Observers, Self::Observers> {
            RefIndexable::from(&self.observers)
        }

        fn observers_mut(&mut self) -> RefIndexable<&mut Self::Observers, Self::Observers> {
            RefIndexable::from(&mut self.observers)
        }
    }

    impl<EM, S, Z> Executor<EM, BytesInput, S, Z> for DummyPrimaryExecutor {
        fn run_target(
            &mut self,
            _fuzzer: &mut Z,
            _state: &mut S,
            _mgr: &mut EM,
            _input: &BytesInput,
        ) -> Result<ExitKind, Error> {
            Ok(ExitKind::Ok)
        }
    }

    #[derive(Debug)]
    struct DummySecondaryExecutor {
        observers: (StdMapObserver<'static, u8, false>, ()),
    }

    impl HasObservers for DummySecondaryExecutor {
        type Observers = (StdMapObserver<'static, u8, false>, ());

        fn observers(&self) -> RefIndexable<&Self::Observers, Self::Observers> {
            RefIndexable::from(&self.observers)
        }

        fn observers_mut(&mut self) -> RefIndexable<&mut Self::Observers, Self::Observers> {
            RefIndexable::from(&mut self.observers)
        }
    }

    impl<EM, S, Z> Executor<EM, BytesInput, S, Z> for DummySecondaryExecutor {
        fn run_target(
            &mut self,
            _fuzzer: &mut Z,
            _state: &mut S,
            _mgr: &mut EM,
            _input: &BytesInput,
        ) -> Result<ExitKind, Error> {
            Ok(ExitKind::Ok)
        }
    }

    #[test]
    fn test_push_stages_tuple_composition() {
        let rand = StdRand::with_seed(1234);
        let mut corpus = InMemoryCorpus::<BytesInput>::new();
        let testcase = Testcase::new(BytesInput::new(vec![1, 2, 3, 4]));
        let id = corpus.add(testcase).unwrap();

        let mut feedback = ConstFeedback::new(true);
        let mut objective = ConstFeedback::new(false);
        let mut state = StdState::new(
            rand,
            corpus,
            InMemoryCorpus::new(),
            &mut feedback,
            &mut objective,
        )
        .unwrap();
        state.set_corpus_id(id).unwrap();

        let mut stages = tuple_list!(
            CalibrationPushStage::with_runs(2),
            StdMutationalPushStage::new(BitFlipMutator::new()),
            TracingPushStage::new()
        );
        let mut mgr = NopEventManager::new();

        PushStagesTuple::<NopEventManager, BytesInput, (StdMapObserver<'static, u8, false>, ()), _>::init_all(&mut stages, &mut state, &mut mgr).unwrap();

        let mut step_count = 0;
        while let StageStep::Execute(_) = PushStagesTuple::<
            NopEventManager,
            BytesInput,
            (StdMapObserver<'static, u8, false>, ()),
            _,
        >::step_all(&mut stages, &mut state, &mut mgr)
        .unwrap()
        {
            step_count += 1;
        }

        assert!(step_count >= 3);
        PushStagesTuple::<NopEventManager, BytesInput, (StdMapObserver<'static, u8, false>, ()), _>::deinit_all(&mut stages, &mut state, &mut mgr).unwrap();
    }

    #[test]
    fn test_push_stage_mid_stage_resumption() {
        let rand = StdRand::with_seed(1234);
        let mut corpus = InMemoryCorpus::<BytesInput>::new();
        let testcase = Testcase::new(BytesInput::new(vec![1, 2, 3, 4]));
        let id = corpus.add(testcase).unwrap();

        let mut feedback = ConstFeedback::new(true);
        let mut objective = ConstFeedback::new(false);
        let mut state = StdState::new(
            rand,
            corpus,
            InMemoryCorpus::new(),
            &mut feedback,
            &mut objective,
        )
        .unwrap();
        state.set_corpus_id(id).unwrap();

        let mut stages = tuple_list!(CalibrationPushStage::with_runs(2), TracingPushStage::new());
        let mut mgr = NopEventManager::new();

        PushStagesTuple::<NopEventManager, BytesInput, (StdMapObserver<'static, u8, false>, ()), _>::init_all(&mut stages, &mut state, &mut mgr).unwrap();

        // Execute stage 1 (Calibration)
        let step1 = PushStagesTuple::<
            NopEventManager,
            BytesInput,
            (StdMapObserver<'static, u8, false>, ()),
            _,
        >::step_all(&mut stages, &mut state, &mut mgr)
        .unwrap();
        assert!(matches!(step1, StageStep::Execute(_)));

        // Simulate resume: stage_id remains valid
        let current_stage = state.current_stage_id().unwrap();
        assert!(current_stage.is_some());

        // Re-initialize stages under resumption
        PushStagesTuple::<NopEventManager, BytesInput, (StdMapObserver<'static, u8, false>, ()), _>::init_all(&mut stages, &mut state, &mut mgr).unwrap();
        let step2 = PushStagesTuple::<
            NopEventManager,
            BytesInput,
            (StdMapObserver<'static, u8, false>, ()),
            _,
        >::step_all(&mut stages, &mut state, &mut mgr)
        .unwrap();
        assert!(matches!(step2, StageStep::Execute(_) | StageStep::Done));

        PushStagesTuple::<NopEventManager, BytesInput, (StdMapObserver<'static, u8, false>, ()), _>::deinit_all(&mut stages, &mut state, &mut mgr).unwrap();
    }

    #[test]
    fn test_push_engine_with_various_schedulers() {
        // 1. QueueScheduler
        {
            let rand = StdRand::with_seed(100);
            let mut corpus = InMemoryCorpus::<BytesInput>::new();
            let id = corpus
                .add(Testcase::new(BytesInput::new(vec![1, 2])))
                .unwrap();
            let mut fb = ConstFeedback::new(true);
            let mut obj = ConstFeedback::new(false);
            let mut state =
                StdState::new(rand, corpus, InMemoryCorpus::new(), &mut fb, &mut obj).unwrap();
            let mut scheduler = QueueScheduler::new();
            crate::schedulers::Scheduler::on_add(&mut scheduler, &mut state, id).unwrap();

            let stages = tuple_list!(CalibrationPushStage::with_runs(1));
            let mut engine = StdFuzzer::new(scheduler, fb, obj, stages);
            let mut mgr = NopEventManager::new();
            let res: EngineStep<BytesInput> = FuzzingEngine::<
                NopEventManager,
                BytesInput,
                (StdMapObserver<'static, u8, false>, ()),
                _,
            >::step(&mut engine, &mut state, &mut mgr)
            .unwrap();
            assert!(matches!(res, EngineStep::Execute(_)));
        }

        // 2. WeightedScheduler / PowerQueueScheduler
        {
            let map_ptr = &raw mut OBS_MAP as *mut u8;
            let observer = unsafe { StdMapObserver::from_mut_ptr("sched_cov1", map_ptr, 16) };
            let rand = StdRand::with_seed(101);
            let mut corpus = InMemoryCorpus::<BytesInput>::new();
            let mut tc = Testcase::new(BytesInput::new(vec![3, 4]));
            *tc.exec_time_mut() = Some(core::time::Duration::from_millis(10));
            let id = corpus.add(tc).unwrap();
            let mut fb = ConstFeedback::new(true);
            let mut obj = ConstFeedback::new(false);
            let mut state =
                StdState::new(rand, corpus, InMemoryCorpus::new(), &mut fb, &mut obj).unwrap();
            let mut scheduler =
                PowerQueueScheduler::new(&mut state, &observer, PowerSchedule::fast());
            crate::schedulers::Scheduler::on_add(&mut scheduler, &mut state, id).unwrap();

            let stages = tuple_list!(StdPowerMutationalPushStage::new(BitFlipMutator::new()));
            let mut engine = StdFuzzer::new(scheduler, fb, obj, stages);
            let mut mgr = NopEventManager::new();
            let res: EngineStep<BytesInput> = FuzzingEngine::<
                NopEventManager,
                BytesInput,
                (StdMapObserver<'static, u8, false>, ()),
                _,
            >::step(&mut engine, &mut state, &mut mgr)
            .unwrap();
            assert!(matches!(res, EngineStep::Execute(_)));
        }

        // 3. MinimizerScheduler
        {
            let map_ptr = &raw mut OBS_MAP as *mut u8;
            let observer =
                unsafe { StdMapObserver::from_mut_ptr("sched_cov2", map_ptr, 16) }.track_indices();
            let rand = StdRand::with_seed(102);
            let mut corpus = InMemoryCorpus::<BytesInput>::new();
            let mut tc = Testcase::new(BytesInput::new(vec![5, 6]));
            tc.add_metadata(crate::feedbacks::MapIndexesMetadata::new(vec![0]));
            *tc.exec_time_mut() = Some(core::time::Duration::from_millis(10));
            let id = corpus.add(tc).unwrap();
            let mut fb = ConstFeedback::new(true);
            let mut obj = ConstFeedback::new(false);
            let mut state =
                StdState::new(rand, corpus, InMemoryCorpus::new(), &mut fb, &mut obj).unwrap();
            let mut scheduler =
                IndexesLenTimeMinimizerScheduler::new(&observer, QueueScheduler::new());
            crate::schedulers::Scheduler::on_add(&mut scheduler, &mut state, id).unwrap();

            let stages = tuple_list!(CalibrationPushStage::with_runs(1));
            let mut engine = StdFuzzer::new(scheduler, fb, obj, stages);
            let mut mgr = NopEventManager::new();
            let res: EngineStep<BytesInput> = FuzzingEngine::<
                NopEventManager,
                BytesInput,
                (StdMapObserver<'static, u8, false>, ()),
                _,
            >::step(&mut engine, &mut state, &mut mgr)
            .unwrap();
            assert!(matches!(res, EngineStep::Execute(_)));
        }

        // 4. ProbabilitySamplingScheduler
        {
            #[derive(Debug, Clone)]
            struct UniformDistribution;
            impl<I, S> crate::schedulers::TestcaseScore<I, S> for UniformDistribution
            where
                S: crate::state::HasCorpus<I>,
            {
                fn compute(_state: &S, _: &mut Testcase<I>) -> Result<f64, Error> {
                    Ok(1.0)
                }
            }

            let rand = StdRand::with_seed(103);
            let mut corpus = InMemoryCorpus::<BytesInput>::new();
            let tc = Testcase::new(BytesInput::new(vec![7, 8]));
            let id = corpus.add(tc).unwrap();
            let mut fb = ConstFeedback::new(true);
            let mut obj = ConstFeedback::new(false);
            let mut state =
                StdState::new(rand, corpus, InMemoryCorpus::new(), &mut fb, &mut obj).unwrap();
            let mut scheduler =
                crate::schedulers::ProbabilitySamplingScheduler::<UniformDistribution>::new();
            crate::schedulers::Scheduler::on_add(&mut scheduler, &mut state, id).unwrap();

            let stages = tuple_list!(CalibrationPushStage::with_runs(1));
            let mut engine = StdFuzzer::new(scheduler, fb, obj, stages);
            let mut mgr = NopEventManager::new();
            let res: EngineStep<BytesInput> = FuzzingEngine::<
                NopEventManager,
                BytesInput,
                (StdMapObserver<'static, u8, false>, ()),
                _,
            >::step(&mut engine, &mut state, &mut mgr)
            .unwrap();
            assert!(matches!(res, EngineStep::Execute(_)));
        }
    }

    #[test]
    fn test_cmplog_push_stage_pipelining_with_dual_executor() {
        let rand = StdRand::with_seed(999);
        let mut corpus = InMemoryCorpus::<BytesInput>::new();
        let testcase = Testcase::new(BytesInput::new(vec![0x10, 0x20]));
        let id = corpus.add(testcase).unwrap();

        let mut feedback = ConstFeedback::new(true);
        let mut objective = ConstFeedback::new(false);

        let mut state = StdState::new(
            rand,
            corpus,
            InMemoryCorpus::new(),
            &mut feedback,
            &mut objective,
        )
        .unwrap();

        let mut scheduler = QueueScheduler::new();
        crate::schedulers::Scheduler::on_add(&mut scheduler, &mut state, id).unwrap();

        let map_ptr = &raw mut OBS_MAP as *mut u8;
        let primary_obs = unsafe { StdMapObserver::from_mut_ptr("primary_cov", map_ptr, 16) };
        let secondary_obs = unsafe { StdMapObserver::from_mut_ptr("cmplog_cov", map_ptr, 16) };

        let primary_exec = DummyPrimaryExecutor {
            observers: (primary_obs, ()),
        };
        let secondary_exec = DummySecondaryExecutor {
            observers: (secondary_obs, ()),
        };
        let mut dual_exec = DualTargetExecutor::new(
            crate::executors::target::StdTargetExecutor::new(primary_exec),
            crate::executors::target::StdTargetExecutor::new(secondary_exec),
            ExecutionMode::CmpLog,
        );

        let cmplog_stage = AflppCmplogTracingPushStage::new();
        let redqueen_stage =
            MultiMutationalPushStage::new(AflppRedQueen::with_cmplog_options(true, true));
        let stages = tuple_list!(cmplog_stage, redqueen_stage);

        let mut engine = StdFuzzer::new(scheduler, feedback, objective, stages);
        let mut mgr = NopEventManager::new();

        for _ in 0..5 {
            match FuzzingEngine::<
                NopEventManager,
                BytesInput,
                (StdMapObserver<'static, u8, false>, ()),
                _,
            >::step(&mut engine, &mut state, &mut mgr)
            .unwrap()
            {
                EngineStep::Execute(req) => {
                    let res = dual_exec.execute_request(&req).unwrap();
                    engine
                        .report_observations(&mut state, &mut mgr, res)
                        .unwrap();
                }
                EngineStep::Progress => {}
                EngineStep::Completed => break,
            }
        }

        assert!(*crate::state::HasExecutions::executions(&state) > 0);
    }

    #[test]
    fn test_push_stage_adapter_and_zero_overhead_restart() {
        use crate::common::HasNamedMetadata;

        let rand = StdRand::with_seed(1234);
        let mut corpus = InMemoryCorpus::<BytesInput>::new();
        let testcase = Testcase::new(BytesInput::new(vec![1, 2, 3, 4]));
        let id = corpus.add(testcase).unwrap();

        let mut feedback = ConstFeedback::new(true);
        let mut objective = ConstFeedback::new(false);
        let mut state = StdState::new(
            rand,
            corpus,
            InMemoryCorpus::new(),
            &mut feedback,
            &mut objective,
        )
        .unwrap();
        state.set_corpus_id(id).unwrap();

        let mut mgr = NopEventManager::new();
        let mut stage = StdMutationalPushStage::new(BitFlipMutator::new());
        PushStage::<NopEventManager, BytesInput, (), _>::init(&mut stage, &mut state, &mut mgr)
            .unwrap();

        // Advance 2 steps before a simulated crash/restart
        let step1 =
            PushStage::<NopEventManager, BytesInput, (), _>::step(&mut stage, &mut state, &mut mgr)
                .unwrap();
        assert!(matches!(step1, StageStep::Execute(_)));
        let step2 =
            PushStage::<NopEventManager, BytesInput, (), _>::step(&mut stage, &mut state, &mut mgr)
                .unwrap();
        assert!(matches!(step2, StageStep::Execute(_)));

        // Verify progress metadata stored in state reflects exact progress
        let meta = state
            .named_metadata_map()
            .get::<StageProgressMetadata>(stage.name())
            .unwrap();
        let done_before_restart = meta.testcases_done;
        let to_do = meta.testcases_to_do;
        assert_eq!(done_before_restart, 2);

        // Simulate restart: create a fresh stage instance and call init() against restored state
        let mut restarted_stage = StdMutationalPushStage::new(BitFlipMutator::new());
        PushStage::<NopEventManager, BytesInput, (), _>::init(
            &mut restarted_stage,
            &mut state,
            &mut mgr,
        )
        .unwrap();

        let step3 = PushStage::<NopEventManager, BytesInput, (), _>::step(
            &mut restarted_stage,
            &mut state,
            &mut mgr,
        )
        .unwrap();
        assert!(matches!(step3, StageStep::Execute(_)));
        let meta_after = state
            .named_metadata_map()
            .get::<StageProgressMetadata>(restarted_stage.name())
            .unwrap();
        // Resumed immediately at iteration 3 without re-executing iterations 1 or 2!
        assert_eq!(meta_after.testcases_done, done_before_restart + 1);
        assert_eq!(meta_after.testcases_to_do, to_do);
    }
}
