[env]
PROJECT_DIR = { script = ["pwd"] }
CARGO_TARGET_DIR = { value = "${PROJECT_DIR}/target", condition = { env_not_set = ["CARGO_TARGET_DIR"] } }
FUZZER_NAME="fuzzer"
PROFILE = { value = "release", condition = {env_not_set = ["PROFILE"]} }
PROFILE_DIR = {value = "release", condition = {env_not_set = ["PROFILE_DIR"] }}
LLVM_CONFIG = {value = "llvm-config-18", condition = {env_not_set = ["LLVM_CONFIG"] }}
AFL_DIR_NAME= {value = "./AFLplusplus-stable"}
AFL_CC_PATH= {value = "${AFL_DIR_NAME}/afl-clang-fast"}
LIBAFL_FUZZ_PATH={value = "./target/release/libafl-fuzz"}
#LLVM_CONFIG="llvm-config-18"


[tasks.fuzzer]
script_runner="@shell"
script='''
if [ ! -d "$AFL_DIR_NAME" ]; then
	if [ -f "stable.zip" ]; then
		rm stable.zip
	fi
	wget https://github.com/AFLplusplus/AFLplusplus/archive/refs/heads/stable.zip
	unzip stable.zip
	cd $AFL_DIR_NAME
	LLVM_CONFIG=${LLVM_CONFIG} make 
	cd ..
fi

'''
# Test
[tasks.test]
linux_alias = "test_unix"
mac_alias = "test_unix"
windows_alias = "unsupported"

[tasks.test_unix]
script_runner="@shell"
script='''
cargo build --release
AFL_PATH=${AFL_DIR_NAME} ${AFL_CC_PATH} ./test/test-instr.c -o ./test/out-instr
AFL_CORES=1 AFL_STATS_INTERVAL=1 timeout 5 ${LIBAFL_FUZZ_PATH} -i ./test/seeds -o ./test/output ./test/out-instr
test -n "$( ls ./test/output/fuzzer_main/queue/id:000002* 2>/dev/null )" || exit 1
test -n "$( ls ./test/output/fuzzer_main/fuzzer_stats 2>/dev/null )" || exit 1
test -n "$( ls ./test/output/fuzzer_main/plot_data 2>/dev/null )" || exit 1
test -n "$( ls ./test/output/fuzzer_main/crashe2s 2>/dev/null )" || exit 1
test -n "$( ls ./test/output/fuzzer_main/hangs 2>/dev/null )" || exit 1
'''
dependencies = ["fuzzer"]
