[env]
PROJECT_DIR = { script = ["pwd"] }
CARGO_TARGET_DIR = { value = "${PROJECT_DIR}/target", condition = { env_not_set = ["CARGO_TARGET_DIR"] } }
FUZZER_NAME="fuzzer"
PROFILE = { value = "release", condition = {env_not_set = ["PROFILE"]} }
PROFILE_DIR = {value = "release", condition = {env_not_set = ["PROFILE_DIR"] }}
LLVM_CONFIG = {value = "llvm-config-18", condition = {env_not_set = ["LLVM_CONFIG"] }}
AFL_DIR_NAME= {value = "./AFLplusplus-stable"}
AFL_CC_PATH= {value = "${AFL_DIR_NAME}/afl-clang-fast"}
LIBAFL_FUZZ_PATH={value = "./target/release/libafl-fuzz"}
#LLVM_CONFIG="llvm-config-18"


[tasks.fuzzer]
script_runner="@shell"
script='''
if [ ! -d "$AFL_DIR_NAME" ]; then
	if [ -f "stable.zip" ]; then
		rm stable.zip
	fi
	wget https://github.com/AFLplusplus/AFLplusplus/archive/refs/heads/stable.zip
	unzip stable.zip
	cd $AFL_DIR_NAME
	LLVM_CONFIG=${LLVM_CONFIG} make 
	cd ..
fi

'''
# Test
[tasks.test]
linux_alias = "test_unix"
mac_alias = "test_unix"
windows_alias = "unsupported"

[tasks.test_unix]
script_runner="@shell"
script='''
cargo build --release

AFL_LLVM_CMPLOG=1 ${AFL_CC_PATH} -o ./test/test-cmplog ./test/test-cmplog.c > /dev/null 2>&1
AF_CORES=1 AFL_BENCH_UNTIL_CRASH=1 ${LIBAFL_FUZZ_PATH} -Z -l 3 -m none -V30 -i in -o ./test/output_cmplog -c 0 -- ./test/test-cmplog >>errors 2>&1
test -n "$( ls ./test/output_cmplog/default/crashes/id:000000* ./test/output_cmplog/default/hangs/id:000000* 2>/dev/null )" || exit 1
'''
dependencies = ["fuzzer"]
